2024-08-10 03:19:47,119 | WARNING | Неверный тип данных для объекта Runner
Traceback (most recent call last):
  File "C:\Users\Dmitry\PycharmProjects\Urban_Python_12\tests_12_4.py", line 71, in test_run
    running_runner = Runner(5)
                     ^^^^^^^^^
  File "C:\Users\Dmitry\PycharmProjects\Urban_Python_12\tests_12_4.py", line 9, in __init__
    raise TypeError(f'Имя может быть только числом, передано {type(name).__name__}')
TypeError: Имя может быть только числом, передано int
2024-08-10 03:19:47,119 | WARNING | Неверная скорость для Runner
Traceback (most recent call last):
  File "C:\Users\Dmitry\PycharmProjects\Urban_Python_12\tests_12_4.py", line 60, in test_walk
    walking_runner = Runner('Petya', -3)
                     ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dmitry\PycharmProjects\Urban_Python_12\tests_12_4.py", line 14, in __init__
    raise ValueError(f'Скорость не может быть отрицательной, сейчас {speed}')
ValueError: Скорость не может быть отрицательной, сейчас -3
